### ISSUE TITLE
"setUpload is not a function" error on imgModal close

### ISSUE THREAD

**Issue by PeterMyer** [PeterMyer/Byte-RecipeReader#55]
react-dom.development.js:4310 Uncaught TypeError: setUpload is not a function
    at handleClose (ImgModal.js:24:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4162:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4275:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4288:1)
    at executeDispatch (react-dom.development.js:9039:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9071:1)
    at processDispatchQueue (react-dom.development.js:9084:1)
    at dispatchEventsForPlugins (react-dom.development.js:9095:1)
    at react-dom.development.js:9286:1

**Comment by PeterMyer** [comment]
Ticket Closed: Will Not Complete

Img Modal removed in favor of new workflow
